### ISSUE TITLE
MVC project has an error

### ISSUE THREAD

**Issue by feinstein** [brianegan/flutter_architecture_samples#115]
`App.dart` has the following line:

``` 
 /// An external reference to the Controller if you wish. -gp
  static final Con controller = Con();
```

Which is marked as an error:

>Class 'MVCApp' can't define static member 'controller' and have instance member 'AppMVC.controller' with the same name.

**Comment by mmcc007** [comment]
This is a strange one:

If you call
```
flutter build apk --debug
```
... it will give this compiler error...
If you call it a second time, it will compile with no error!

That is why we did not find it in the online integration tests (it does an auto-retry).

For now, to get it to compile change code to:
``` dart
class MVCApp extends AppMVC {
  MVCApp({Key key}) : super(con: appCon, key: key);

  /// An external reference to the Controller if you wish. -gp
  static final Con appCon = Con();
```

**Comment by brianegan** [comment]
Sorry, think I fixed this but forgot to comment -- this one should be all fixed up!
