### ISSUE TITLE
firestore_redux incompatible with Flutter 1.2/Dart 2.2

### ISSUE THREAD

**Issue by arnemolland** [brianegan/flutter_architecture_samples#117]
Running firestore_redux on the latest stable Flutter 1.2 release alongside Dart 2.2 results in the following exception in the ReduxApp constructor:

```
E/flutter (13141): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: type 'List<String>' is not a subtype of type 'ReactiveTodosRepository' of 'todosRepository'
E/flutter (13141): #0      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:185:38)
E/flutter (13141): #1      _rootRun (dart:async/zone.dart:1124:13)
E/flutter (13141): #2      _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter (13141): #3      _runZoned (dart:async/zone.dart:1516:10)
E/flutter (13141): #4      runZoned (dart:async/zone.dart:1500:12)
E/flutter (13141): #5      _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:180:5)
E/flutter (13141): #6      _startIsolate.<anonymous closure> (dart:isolate/runtime/lib/isolate_patch.dart:300:19)
E/flutter (13141): #7      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/lib/isolate_patch.dart:171:12)
```

Could this be redux/flutter_redux related incompatibility issues with the Flutter 1.2/Dart 2.2 release?

**Comment by harshvardhan** [comment]
hey i am also getting the since long now, any resolution to this?
or how can we switch back to the stable version of flutter and dart for this!!

**Comment by mmcc007** [comment]
I looked into this briefly but have not yet located the problem. Until it is resolved, you can downgrade to an earlier version of Flutter that does not have this problem using something like:
```
cd ~/Library/Flutter/flutterSDK
git checkout v1.0.0
flutter doctor -v
```

**Comment by javipacheco** [comment]
Same problem here 😞

**Comment by harshvardhan** [comment]
Hey Javi, i got this resolved by this:
https://stackoverflow.com/questions/54910211/errorflutter-lib-ui-ui-dart-state-cc148-unhandled-exception

**Comment by Caldarie** [comment]
@harshvardhan Thankyou very much!!! It works. All i did was remove the parameters, for example:
OLD CODE
`// void main([
//   ReactiveTodosRepository todosRepository, //manages todo
//   UserRepository userRepository, //manages users
// ]) {
//   runApp(TeacherApp( //inflates the widget - TeacherApp (note how overide is a widget in TeacherAPp class)
//     todosRepository: todosRepository, //optional named parameter
//     userRepository: userRepository, //optional named parameter
//   )); 
// }`

NEW CODE
`void main() {
  //inflates the widget - TeacherApp (note how overide is a widget in TeacherAPp class)
  runApp(TeacherApp()); 
}`
