### ISSUE TITLE
Return value from loading state reducer

### ISSUE THREAD

**Issue by craigomac** [brianegan/flutter_architecture_samples#126]
https://github.com/brianegan/flutter_architecture_samples/blob/54704bd915f0f14ec64dd04317971bcd978c6cc0/redux/lib/reducers/loading_reducer.dart#L14

Thanks for a great redux sample. One thing confuses me, and I wonder if it's an issue. Why isn't this line `return true` or return `false` based on the action?

**Comment by brianegan** [comment]
Hey there! In that example, it's using a TypedReducer to return that value in response to a TodosLoadedAction. In the loading case, we don't need data from the action, but just use it as a signal to know we can set loading to false.

**Comment by craigomac** [comment]
Ah, I think my mistake was in parsing this:

```
bool _setLoaded(bool state, action) {
  return false;
}
```

What it's actually indicating with the return value is that it's no longer *loading*, not whether the data is successfully `loaded` or not. My mistake! Thanks!
