### ISSUE TITLE
Sharing Data / Domain layer with Angular App

### ISSUE THREAD

**Issue by brianegan** [brianegan/flutter_architecture_samples#13]
Extract the business logic from the Redux app into a separate package and share it with an Angular todo app. Demonstrates the importance /advantages of layering.

**Comment by gedw99** [comment]
+1

This is exactly what I am hoping to see.

There are currently a few approaches out there but it would be great too see a working prototype of a flutter and angular app sharing as much code as possible.

**Comment by brianegan** [comment]
Cool, thanks for the heads up! I'll "bump it up in priority" :)

**Comment by franklinharper** [comment]
+1! This was on my wish list too. Glad to see there's already an issue.

**Comment by brianegan** [comment]
Thanks for the feedback! Been super busy lately, but hoping to contribute more  soon :)

**Comment by brianegan** [comment]
Closing this in favor of Flutter Web support
