### ISSUE TITLE
Observable.combineLatest2 return no result on rxdart 0.21.0

### ISSUE THREAD

**Issue by tz182736** [brianegan/flutter_architecture_samples#132]
no issues on rxdart 0.18.0 and working fine, 

issuse with new flutter rxdart package 0.21.0 only

issues reside in flutter_architecture_samples-master\blocs\lib\src\todos_list_bloc.dart

    // To calculate the visible todos, we combine the todos with the current
    // visibility filter and return the filtered todos.
    //
    // Every time the todos or the filter changes the visible items will emit
    // once again. We also convert the normal Stream into a BehaviorSubject
    // so the Stream can be listened to multiple times
    final visibleTodosController = BehaviorSubject<List<Todo>>();

    Observable.combineLatest2<List<Todo>, VisibilityFilter, List<Todo>>(
      interactor.todos,
      updateFilterController.stream,
      _filterTodos,
    ).pipe(visibleTodosController);

**Comment by nigelpasco** [comment]
Is the issue there? or up further due to the use removal of (seedValue, ...) in rxdart v0.21.

Replace final updateFilterController line to:
 final updateFilterController = BehaivourSubject<VisibliltyFilter>.seeded(...

Refer to the rxdart changelog for details.

**Comment by nigelpasco** [comment]
what is the error that you are getting?

I am having error with the Injector not being passed in, or being passed in as null

**Comment by brianegan** [comment]
Hey all -- I've updated to the latest RxDart 0.23.x and think I've fixed all these issues. Please let me know if you run into more trouble!
