### ISSUE TITLE
Provider example

### ISSUE THREAD

**Issue by DFreds** [brianegan/flutter_architecture_samples#134]
With the support of the new Provider library (as shown [here](https://www.youtube.com/watch?v=d_m5csmrf7I)), I think a new example would be worthwhile. It might help others weigh the pros and cons of it versus BLoC or Scoped Model.

Relevant docs: https://pub.dev/packages/provider

**Comment by brianegan** [comment]
Yep, makes sense! Overall, the example will be almost Identical to the `scoped_model` example.

Instead of extending the `Model` class, you'll either mixin or extend the `ChangeNotifier` class.

Instead of `ScopedModel` / `ScopedModelDescendant`, you'd use `ChangeNotifierProvider` & `Consumer`.

**Comment by shakib609** [comment]
I already created a similar app with `provider` [here](https://github.com/shakib609/todos-flutter/). I will submit a PR after making necessary changes.

**Comment by tuanbs** [comment]
@shakib609 Thanks for the example using `Provider`, but after running the app, I see your app doesn't follow the [app specification](https://github.com/brianegan/flutter_architecture_samples/blob/master/app_spec.md). It's better if you make it consistent with the spec.

**Comment by shakib609** [comment]
@tuanbs I modified the ScopedModel example app to use Provider as @brianegan suggested.
Did you by any chance checked [this app](https://github.com/shakib609/todos-flutter)?

**Comment by tuanbs** [comment]
@shakib609 Yes I checked and run [that app](https://github.com/shakib609/todos-flutter) but the UI is different from the [app spec](https://github.com/brianegan/flutter_architecture_samples/blob/master/app_spec.md). I also checked the [scoped_model example](https://github.com/brianegan/flutter_architecture_samples/tree/master/scoped_model) but I see it doesn't use `provider` in `pubspec.yaml`. Also, I'm able to run the [scoped_model example](https://github.com/brianegan/flutter_architecture_samples/tree/master/scoped_model) on Android, but it doesn't work on iOS.

**Comment by shakib609** [comment]
@tuanbs The app in my profile was not intended for this PR. Please check [this one](https://github.com/shakib609/flutter_architecture_samples/tree/provider-sample/provider).

**Comment by tuanbs** [comment]
Hi @shakib609, thanks for this, it works now. I have to download the zip file (NOT the `git clone ...` cli) from [here](https://github.com/shakib609/flutter_architecture_samples/tree/provider-sample) to get the provider example.

Also, I found you have [the tutorial](https://dev.to/shakib609/create-a-todos-app-with-flutter-and-provider-jdh) for this provider-example, but it's about your [old app](https://github.com/shakib609/todos-flutter). So I think you should update this tutorial with the [new one](https://github.com/shakib609/flutter_architecture_samples/tree/provider-sample/provider).
@brianegan It's better if you could include the tutorial for each example in the `README` file. For example, I found the `flutter_bloc` example has [this tutorial](https://medium.com/flutter-community/flutter-todos-tutorial-with-flutter-bloc-d9dd833f9df3) as well.
Anyway, thank you very much for your great jobs guys. I learned a lot from it. Cheers.
