### ISSUE TITLE
Unable to run bloc_library

### ISSUE THREAD

**Issue by bmcilw1** [brianegan/flutter_architecture_samples#136]
Hi there! I'm a noob doing my best to get your project running. I think that I found a potential package version conflict in the bloc_library project.

```
flutter pub get pubspec.yaml 
Because every version of todos_repository_simple from git depends on rxdart ^0.22.0 and bloc >=0.10.0 <0.13.0 depends on rxdart ^0.
21.0, todos_repository_simple from git is incompatible with bloc >=0.10.0 <0.13.0.
And because flutter_bloc >=0.9.0 <0.11.0 depends on bloc ^0.11.0, todos_repository_simple from git is incompatible with flutter_blo
c >=0.9.0 <0.11.0.
So, because bloc_library depends on both flutter_bloc ^0.10.0 and todos_repository_simple from git, version solving failed.
Running "flutter packages get" in ....                                  
pub get failed (1)
```

This error went away when I incremented the below in the pubspec.yaml:
`flutter_bloc: ^0.10.0` to `flutter_bloc: ^0.13.0`

After getting past this error, I got stuck on the below error.
```
flutter run -d iPhon
Launching lib/main.dart on iPhone 8 in debug mode...

Compiler message:
lib/blocs/simple_bloc_delegate.dart:11:8: Error: The method 'SimpleBlocDelegate.onTransition' has fewer positional arguments than
those of overridden method 'BlocDelegate.onTransition'.
  void onTransition(Transition transition) {
       ^
file:///Users/brian.mcilwain/source/flutter/.pub-cache/hosted/pub.dartlang.org/bloc-0.13.0/lib/src/bloc_delegate.dart:17:8:
Context: This is the overridden method ('onTransition').
  void onTransition(Bloc bloc, Transition transition) => null;
       ^
lib/blocs/simple_bloc_delegate.dart:11:32: Error: The parameter 'transition' of the method 'SimpleBlocDelegate.onTransition' has
type 'Transition<dynamic, dynamic>', which does not match the corresponding type, 'Bloc<dynamic, dynamic>', in the overridden
method, 'BlocDelegate.onTransition'.
 - 'Transition' is from 'package:bloc/src/transition.dart'
 ('file:///Users/brian.mcilwain/source/flutter/.pub-cache/hosted/pub.dartlang.org/bloc-0.13.0/lib/src/transition.dart').
 - 'Bloc' is from 'package:bloc/src/bloc.dart'
 ('file:///Users/brian.mcilwain/source/flutter/.pub-cache/hosted/pub.dartlang.org/bloc-0.13.0/lib/src/bloc.dart').
Change to a supertype of 'Bloc<dynamic, dynamic>', or, for a covariant parameter, a subtype.
  void onTransition(Transition transition) {
                               ^
file:///Users/brian.mcilwain/source/flutter/.pub-cache/hosted/pub.dartlang.org/bloc-0.13.0/lib/src/bloc_delegate.dart:17:8:
Context: This is the overridden method ('onTransition').
  void onTransition(Bloc bloc, Transition transition) => null;
       ^
lib/blocs/simple_bloc_delegate.dart:17:8: Error: The method 'SimpleBlocDelegate.onError' has fewer positional arguments than those
of overridden method 'BlocDelegate.onError'.
  void onError(Object error, StackTrace stacktrace) {
       ^
file:///Users/brian.mcilwain/source/flutter/.pub-cache/hosted/pub.dartlang.org/bloc-0.13.0/lib/src/bloc_delegate.dart:24:8:
Context: This is the overridden method ('onError').
  void onError(Bloc bloc, Object error, StackTrace stacktrace) => null;
       ^
lib/blocs/simple_bloc_delegate.dart:17:41: Error: The parameter 'stacktrace' of the method 'SimpleBlocDelegate.onError' has type
'StackTrace', which does not match the corresponding type, 'Object', in the overridden method, 'BlocDelegate.onError'.
 - 'StackTrace' is from 'dart:core'.
 - 'Object' is from 'dart:core'.
Change to a supertype of 'Object', or, for a covariant parameter, a subtype.
  void onError(Object error, StackTrace stacktrace) {
                                        ^
file:///Users/brian.mcilwain/source/flutter/.pub-cache/hosted/pub.dartlang.org/bloc-0.13.0/lib/src/bloc_delegate.dart:24:8:
Context: This is the overridden method ('onError').
  void onError(Bloc bloc, Object error, StackTrace stacktrace) => null;
       ^
lib/blocs/simple_bloc_delegate.dart:12:23: Error: Too few positional arguments: 2 required, 1 given.
    super.onTransition(transition);
                      ^
lib/blocs/simple_bloc_delegate.dart:18:18: Error: Too few positional arguments: 3 required, 2 given.
    super.onError(error, stacktrace);
                 ^
Compiler failed on /Users/brian.mcilwain/source/flutter_architecture_samples/bloc_library/lib/main.dart
Error launching application on iPhone 8.
```

What I noticed in VSCode was that I was getting an import statement saying that a file wasn't found `import 'package:bloc/bloc.dart';`, which was in `lib/blocs/simple_bloc_delegate.dart`. Should this come from a plugin? Is a package no longer working on version 13 that I changed to fix the above bug?

I believe at least some of these things are not expected and I hope this one's not just me, but if I'm missing something on how to run the project please respond or add it to the README.

Thank you!

**Comment by mmcc007** [comment]
The change in dependency in https://github.com/felangel/flutter_architecture_samples/commit/08da0c362ff3b46bc5cdc26e43fcde4d3895e72a is causing this problem.

Adding
```
  rxdart: '0.21.0'
```
to dependency_overrides section in bloc_library/pubspec.yaml should fix it for now. 

(Reason why external dependencies are used in dependency_overrides section in bloc_library/pubspec.yaml should probably be resolved)

**Comment by bmcilw1** [comment]
Thanks, @mmcc007! Adding rxdart to dependency_overrides fixes the problem. I'm now able to run the project. I guess this should be addressed in a more permanent way if possible.

**Comment by felangel** [comment]
@mmcc007 the problem is the bloc library has a dependency on `rxdart ^0.22.0` which conflicts with `todos_repository_simple`. I'll create a PR to update the `rxdart` version across all examples 👍

**Comment by mmcc007** [comment]
Yes, seems like we should strive to use a consistent (preferably the latest) version of `rxdart` where it makes sense.

Those projects that depend on `todos_repository_simple` may break as a result. Looks like they will have to be fixed. Ideally those familiar with those projects can fix their apps. But looks like in practice we may have to find another way to fix those apps.

@brianegan any suggestions (I'm not that familiar with `rxdart` and what has changed in `rxdart`)?

**Comment by felangel** [comment]
@mmcc007 from what I’ve seen it’s mostly seeding behavior subjects that needs to be updated. I don’t think it will require significant effort and majority of the samples will work without any changes from what I can tell. Would love to hear @brianegan’s thoughts as well 👍

**Comment by mmcc007** [comment]
Fixed build for now by overriding external dependency.
On a perhaps unrelated note: looks like upgrading to current version of flutter on stable channel (1.5.4-hotfix.2) will require upgrading libraries:
https://travis-ci.com/mmcc007/flutter_architecture_samples/jobs/205043949

**Comment by felangel** [comment]
@mmcc007 do you want me to close #138?

**Comment by mmcc007** [comment]
@felangel see my response in #137
