### ISSUE TITLE
no examples for concatMap

### ISSUE THREAD

**Issue by Xgamefactory** [brianegan/flutter_architecture_samples#141]
i have watched your video at ReactiveConf2018 with Filip but did not found any examples for contactMap

**Comment by brianegan** [comment]
Hey there! Thanks for writing in. This repo does not need the concatMap operator, so I have not included it here.

This project has some infinite pagination and uses concatMap, but be warned: It's a bit of an experimental app and might be slightly harder to understand. Sorry I don't have a clean example of this!

https://github.com/brianegan/mvi_sealed_unions
