### ISSUE TITLE
Question about overriding ==

### ISSUE THREAD

**Issue by garyivy** [brianegan/flutter_architecture_samples#154]
Why does have does the operator == overload need more than just identical(this, other).

If reducers always return the passed in state instance if no action matches and a new instance when an action matches, why do we need to check each property.

Example:

bool operator ==(Object other) =>
      identical(this, other)

Versus

bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppState &&
          runtimeType == other.runtimeType &&
          isLoading == other.isLoading &&
          todos == other.todos &&
          activeTab == other.activeTab &&
          activeFilter == other.activeFilter;

**Comment by brianegan** [comment]
Hey there -- I usually do that for testing, but it's actually unnecessary here and could be removed. Good catch!
