### ISSUE TITLE
which architecture is the better one?

### ISSUE THREAD

**Issue by guixin567** [brianegan/flutter_architecture_samples#158]
mvvm is the better one for android,so i want to know which is the better one for flutter

**Comment by mmcc007** [comment]
This might help:
https://www.youtube.com/watch?v=d_m5csmrf7I
https://www.youtube.com/watch?v=zKXz3pUkw9A

**Comment by pouledodue** [comment]
rxvms

**Comment by guixin567** [comment]
> This might help:
> https://www.youtube.com/watch?v=d_m5csmrf7I
> https://www.youtube.com/watch?v=zKXz3pUkw9A

thanks

**Comment by brianegan** [comment]
At the end of the day, the "best" architecture is the one that fits your product, business and team's goals. Different architectures are good or bad for different teams and goals.

As the best place to get started, I'd follow the Flutter team's current advice: ChangeNotifier + Provider package.
