### ISSUE TITLE
states_rebuilder sample

### ISSUE THREAD

**Issue by GIfatahTH** [brianegan/flutter_architecture_samples#171]
Hello there, can I open a pull request to add states_rebuilder implementation of the todoMVC app
https://pub.dev/packages/states_rebuilder

**Comment by brianegan** [comment]
Sure, that'd be fantastic :) Please follow the app spec found here and have fun! https://github.com/brianegan/flutter_architecture_samples/blob/master/app_spec.md

If you need any help, please feel free to open an early PR and ask for feedback.
