### ISSUE TITLE
Is this repo dead?

### ISSUE THREAD

**Issue by mjablecnik** [brianegan/flutter_architecture_samples#198]
@brianegan 
Is this project dead? Because I see a lot of PR or Issues which is nobody resolving from April of last year..

**Comment by brianegan** [comment]
Not dead, but I hope you can understand that a combination of being personally busier + covid fatigue make it harder to put in the lots and lots of time this project requires.

**Comment by mjablecnik** [comment]
Yes I understand it.. But is some possibility to add somebody rights for maintenance? Because I have a some time for this weekend so I can go to through pull requests and some issues and resolve it when I will have the rights.. :)

**Comment by FrancisIje** [comment]
@brianegan @mjablecnik  any update on this? I was really hoping to learn a lot from this repo but it seems everything is outdated.
