### ISSUE TITLE
Getting error on pub get in built_redux package

### ISSUE THREAD

**Issue by matejthetree** [brianegan/flutter_architecture_samples#20]
`Running "flutter packages get" in built_redux...
Package build_runner has no versions that match >=0.5.0 <0.6.0 derived from:
- built_redux_sample depends on version ^0.5.0
pub get failed (1)
Process finished with exit code 1`

This is the error I get. I am on 0.1.4 flutter and the latest on this repository.

What could be the issue. Using IntelliJ

**Comment by passsy** [comment]
The error message doesn't point to the real problem. [this](https://github.com/dart-lang/pub/issues/912) is the tracking issue for this problem. Seems like it's currently in active development.

Meanwhile use https://pub.dartlang.org/packages/pub_mediator to find the real conflict.

**Comment by matejthetree** [comment]
I listened to your advice. I got even weirder error from pub_mediator

`Invalid argument(s): Invalid dependency: {"sdk":"flutter"}
#0      resolvePubspec (package:pub_mediator/src/diagnose.dart:248)
<asynchronous suspension>
#1      diagnoseConflicts.<anonymous closure> (package:pub_mediator/src/diagnose.dart:44)
#2      _HashVMBase&MapMixin&&_LinkedHashMapMixin.forEach (dart:collection-patch/dart:collection/compact_hash.dart:361)
#3      diagnoseConflicts (package:pub_mediator/src/diagnose.dart:39)
#4      main (file:///Users/matejsimunic/.pub-cache/hosted/pub.dartlang.org/pub_mediator-1.0.1/bin/main.dart:22)
<asynchronous suspension>
#5      _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#6      _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
`

**Comment by passsy** [comment]
I can reproduce this error on `flutter channel master`. It works fine after switching to `flutter channel beta`

**Comment by matejthetree** [comment]
I am on dev, so its just few steps below master. I will go to dev and try it out. I am not knowledgable what to report to the flutter team. Should we report bug?

**Comment by davidmarne** [comment]
@matejthetree looks like its just due to some outdated deps
I put up a pr with the updates [here](https://github.com/brianegan/flutter_architecture_samples/pull/23)

FWIW I had a successful
`flutter master channel`
`flutter packages get`
`dart tool/build.dart`
`flutter run`

with the updates on 2.0.0-dev.30.0
