### ISSUE TITLE
Support Dart2

### ISSUE THREAD

**Issue by brianegan** [brianegan/flutter_architecture_samples#24]
Running into a few type errors

```
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...
Resolving dependencies...
Running 'gradlew assembleDebug'...
compiler message: file:///media/scott/Data%20SSD/Coding/Flutter/Git%20Projects/Brians%20Stuff/lib/src/localization.dart:13:55: Error: A value of type '(dart.core::Null) → #lib1::ArchSampleLocalizations' can't be assigned to a variable of type '(dynamic) → dart.async::FutureOr<#lib1::ArchSampleLocalizations>'.
compiler message: Try changing the type of the left hand side, or casting the right hand side to '(dynamic) → dart.async::FutureOr<#lib1::ArchSampleLocalizations>'.
compiler message: return initializeMessages(locale.toString()).then((Null value) {
compiler message: ^
Built build/app/outputs/apk/app-debug.apk (28.3MB).
Installing build/app/outputs/apk/app.apk...
I/FlutterActivityDelegate(20357): onResume setting current activity to this
E/flutter (20357): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] error: Unsupported tag at this point: 14.
E/flutter (20357): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Dart_GetClosure expects argument 'library' to be non-null.
D/EGL_emulation(20357): eglMakeCurrent: 0xa84058a0: ver 2 0 (tinfo 0x9141c150)
Syncing files to device Android SDK built for x86...
compiler message: Unhandled exception:
compiler message: NoSuchMethodError: The getter 'dependencies' was called on null.
compiler message: Receiver: null
compiler message: Tried calling: dependencies
compiler message: #0 Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
compiler message: #1 BinaryBuilder.readLibraryDependencyReference (package:kernel/binary/ast_from_binary.dart:535)
compiler message: #2 BinaryBuilder.readExpression (package:kernel/binary/ast_from_binary.dart:1179)
compiler message: #3 BinaryBuilder.readExpressionOption (package:kernel/binary/ast_from_binary.dart:1167)
compiler message: #4 BinaryBuilder.readVariableDeclaration (package:kernel/binary/ast_from_binary.dart:1787)
compiler message: #5 BinaryBuilder.readExpression (package:kernel/binary/ast_from_binary.dart:1384)
compiler message: #6 BinaryBuilder.readExpressionOption (package:kernel/binary/ast_from_binary.dart:1167)
compiler message: #7 BinaryBuilder.readStatement (package:kernel/binary/ast_from_binary.dart:1541)
compiler message: #8 BinaryBuilder.readStatementList (package:kernel/binary/ast_from_binary.dart:1441)
compiler message: #9 BinaryBuilder.readBlock (package:kernel/binary/ast_from_binary.dart:1605)
compiler message: #10 BinaryBuilder.readStatement (package:kernel/binary/ast_from_binary.dart:1465)
compiler message: #11 BinaryBuilder.readSwitchCaseInto (package:kernel/binary/ast_from_binary.dart:1579)
compiler message: #12 BinaryBuilder.readStatement (package:kernel/binary/ast_from_binary.dart:1525)
compiler message: #13 BinaryBuilder.readStatementList (package:kernel/binary/ast_from_binary.dart:1441)
compiler message: #14 BinaryBuilder.readBlock (package:kernel/binary/ast_from_binary.dart:1605)
compiler message: #15 BinaryBuilder.readStatement (package:kernel/binary/ast_from_binary.dart:1465)
compiler message: #16 BinaryBuilder.readStatementOption (package:kernel/binary/ast_from_binary.dart:1456)
compiler message: #17 BinaryBuilder._setLazyLoadFunction.<anonymous closure> (package:kernel/binary/ast_from_binary.dart:1118)
compiler message: #18 FunctionNode._buildLazy (package:kernel/ast.dart:1918)
compiler message: #19 FunctionNode.body (package:kernel/ast.dart:1923)
compiler message: #20 BinaryPrinter.visitFunctionNode (package:kernel/binary/ast_to_binary.dart:881)
compiler message: #21 FunctionNode.accept (package:kernel/ast.dart:1978)
compiler message: #22 BinaryPrinter.writeNode (package:kernel/binary/ast_to_binary.dart:220)
compiler message: #23 LimitedBinaryPrinter.writeNode (package:kernel/binary/limited_ast_to_binary.dart:55)
compiler message: #24 BinaryPrinter.writeOptionalNode (package:kerne
```

**Comment by franklinharper** [comment]
This is the error I am getting.

redux [master]$ flutter run --preview-dart-2
Launching lib/main.dart on iPhone X in debug mode...
Lost connection to device.
Syncing files to device iPhone X...
redux [master]$ flutter run --preview-dart-2
Launching lib/main.dart on iPhone X in debug mode...
Running pod install...                                1.5s
Running Xcode clean...                                0.8s
Starting Xcode build...
 ├─Assembling Flutter resources...             3.5s
 └─Compiling, linking and signing...           2.6s
Xcode build done                                      7.6s
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following NoSuchMethodError was thrown building StoreConnector<AppState,
Store<AppState>>(dirty):
The getter 'store' was called on null.
Receiver: null
Tried calling: store

When the exception was thrown, this was the stack:
#0      Object.noSuchMethod (dart:core/object_patch.dart:46:5)
#1      StoreConnector.build (package:flutter_redux/flutter_redux.dart:134:46)
#2      StatelessElement.build (package:flutter/src/widgets/framework.dart:3678:28)
#3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3625:15)
#4      Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#5      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#6      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#7      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#8      Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#9      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#10     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#11     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#12     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#13     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#14     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#15     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#16     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#17     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#18     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#19     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#20     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#21     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#22     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#23     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#24     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#25     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#26     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#27     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4611:14)
#28     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#29     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4716:32)
#30     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#31     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#32     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#33     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#34     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#35     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3741:11)
#36     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#37     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#38     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#39     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4611:14)
#40     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#41     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#42     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#43     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#44     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#45     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3741:11)
#46     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#47     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#48     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#49     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4611:14)
#50     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#51     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#52     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#53     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#54     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#55     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3741:11)
#56     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#57     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#58     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#59     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4611:14)
#60     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#61     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#62     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#63     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#64     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#65     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3741:11)
#66     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#67     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#68     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#69     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#70     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#71     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#72     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#73     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#74     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#75     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4611:14)
#76     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#77     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#78     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4611:14)
#79     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#80     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#81     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#82     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#83     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#84     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#85     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#86     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#87     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4611:14)
#88     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#89     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#90     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#91     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#92     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#93     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3741:11)
#94     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#95     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#96     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#97     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#98     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#99     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#100    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3741:11)
#101    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#102    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#103    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#104    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#105    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#106    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#107    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3741:11)
#108    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#109    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#110    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4716:32)
#111    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#112    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#113    _TheatreElement.mount (package:flutter/src/widgets/overlay.dart:493:16)
#114    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#115    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#116    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#117    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#118    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#119    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3741:11)
#120    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#121    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#122    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#123    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#124    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#125    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#126    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#127    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#128    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#129    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4611:14)
#130    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#131    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#132    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#133    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#134    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#135    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3741:11)
#136    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#137    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#138    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#139    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4611:14)
#140    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#141    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#142    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4611:14)
Syncing files to device iPhone X...
#143    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#144    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#145    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#146    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#147    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#148    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3741:11)
#149    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#150    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#151    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#152    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#153    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#154    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#155    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#156    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#157    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#158    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4611:14)
#159    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#160    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#161    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#162    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#163    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#164    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#165    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#166    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#167    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#168    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#169    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#170    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#171    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#172    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#173    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#174    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#175    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#176    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#177    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#178    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#179    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#180    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#181    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#182    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#183    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#184    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#185    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#186    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#187    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#188    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#189    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#190    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#191    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#192    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#193    StatefulElement.update (package:flutter/src/widgets/framework.dart:3760:5)
#194    Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
#195    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#196    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#197    ProxyElement.update (package:flutter/src/widgets/framework.dart:3870:5)
#198    Element.updateChild (package:flutter/src/widgets/framework.dart:2682:15)
#199    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#200    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#201    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2225:33)
#202    ______BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:621:20)
#203    _____BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
#204    ___BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
#205    ___BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
#206    ___BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:751:7)
#208    _Timer._runTimers (dart:isolate/timer_impl.dart:382:19)
#209    _Timer._handleMessage (dart:isolate/timer_impl.dart:416:5)
#210    _RawReceivePortImpl._handleMessage (dart:isolate/isolate_patch.dart:165:12)
(elided one frame from package dart:async)
════════════════════════════════════════════════════════════════════════════════════════════════════
Another exception was thrown: NoSuchMethodError: The getter 'store' was called on null.

**Comment by brianegan** [comment]
@franklinharper Thanks for the report! Just as a heads up: these are only compatible with Dart 1 for the time being.

I'm gonna hold off on Dart 2 until I can get all the supporting libs updated for Dart 2 in a stable manner (Rx, Redux, flutter_redux, etc!).

**Comment by DavidMihola** [comment]
So, for anyone else running into this error - this has worked for me (in Android Studio):
* Crtl-Shift-A
* Search for "Flutter - Settings"
* Under "App Execution" change "Run applications in Dart 2.0 mode" to "Disable Dart 2.0"

**Comment by franklinharper** [comment]
Thanks Brian!
