### ISSUE TITLE
Hot reloading rejected

### ISSUE THREAD

**Issue by jack4git** [brianegan/flutter_architecture_samples#29]
This happens to be when running the Redux example. Guessing it probably impacts all the examples.

Appears to be related to deferred loading: 
"Hot reload was rejected:
Reloading support for deferred loading has not yet been implemented: library 'package:flutter/src/gestures/converter.dart' has deferred import 'messages_en'"

**Comment by brianegan** [comment]
Oh dang, hadn't seen that on my! Thanks for the report. I've changed the way the localizations work so this shouldn't happen any more :)

**Comment by jack4git** [comment]
Awesome, thanks. I was having trouble tracking down the root cause, the referenced converter.dart file wasn't doing any deferred loading that I could find!

**Comment by jack4git** [comment]
And confirmed it works.
