### ISSUE TITLE
Update built_redux example when Dart 2 version is stable

### ISSUE THREAD

**Issue by babernethy** [brianegan/flutter_architecture_samples#39]
I am having an issue with the build_redux example, in getting the build_runner to run in the project.

![flutter_built_redux](https://user-images.githubusercontent.com/3207230/39055226-a33ddab2-4481-11e8-8ef8-09a9a7e7c152.PNG)

The app runs fine, and I can see the code, and how its implemented, but I was hoping to learn about the different built components by using the project.

I have a number of projects working locally with built_value and built_collections - trying to find the right configuration to move into the built_redux/flutter_built_redux world.

Really just a working project with the requisite packages/version (pubspec.yaml) and build_runner working would be a great step - I was hoping these examples might be a start.

**Comment by brianegan** [comment]
Hey, sorry about the trouble! The author of built_redux is working on some updates for Dart 2: https://github.com/davidmarne/built_redux/tree/dart-2-dev

Once that is stable and published, I'll update the examples here.

Thanks for writing in :)

**Comment by babernethy** [comment]
Brian - thanks for the quick reply, and all the work and examples (and videos)

I was able to add the "dev" package of built_redux to a project with built_action/collections in it and get it to run with the instructions on the link you shared (thanks!).  This will help move forward with the actions/reducers.  Looks like regular work getting done on these which is great.

Once the code is out of dev, and the flutter package is updated, then I'm sure the samples will move very quickly. Thanks again.

**Comment by brianegan** [comment]
Sure thing! Glad these are helpful. Also, it's pretty confusing, but there are about 18 "Brians" in this community, haha. Gotta give props to Brian Cairs for the youtube vids :)

**Comment by brianegan** [comment]
Updated the built_value example to use the Dev branch since Dart 2 is enabled by default in the IntelliJ plugin. Please consult the updated README for instructions on building!
