### ISSUE TITLE
Firebase Example

### ISSUE THREAD

**Issue by brianegan** [brianegan/flutter_architecture_samples#4]

**Comment by mikemimik** [comment]
I would love to help with this example. I already have a really simple example locally I used to learn how to get firebase and redux working together. I'd love to clean it up and submit it to this project.

**Comment by brianegan** [comment]
Sounds great! Any contributions would be very welcome :)

**Comment by franklinharper** [comment]
Can this be closed, now that we have #30 merged?

**Comment by brianegan** [comment]
@franklinharper Yep! Thanks for spotting that :)
