### ISSUE TITLE
MVU example

### ISSUE THREAD

**Issue by p69** [brianegan/flutter_architecture_samples#40]
Looks like Flutter is perfect for Model View Update (or The Elm Architecture) pattern.
I've already created example and would love to create PR and contribute :raising_hand_man:

**Comment by brianegan** [comment]
Yep, sounds great! Please try your best to fulfill the app spec: https://github.com/brianegan/flutter_architecture_samples/blob/master/app_spec.md

Once you feel good about that, please submit a PR. Thanks so much for contributing :)

**Comment by brianegan** [comment]
@p69 Thanks again for contributing! I'll go ahead and close this one down :)
