### ISSUE TITLE
Where to put data cache logic?

### ISSUE THREAD

**Issue by dustin-graham** [brianegan/flutter_architecture_samples#41]
Regarding Redux architecture (in my case I'm using Epics). 

Suppose that you've written an epic that does some pretty expensive work. you'd like to let the app use the cached result to a certain extent. Given that it's important to have things be pure functions, where have you found it appropriate to cache state and prevent the client from requesting repeated resources etc? I can see that from my epic I have access to the store, I could find a state flag that tells me the last time I updated this expensive resource and decline to fetch an update if a condition is not met. I could pass the responsibility to be a good citizen down to view consumers but that seems too much responsibility in too many places. 

Put another way: If I kick off an action during the init function of my connected widget, and that is handled by an Epic that does expensive work, what's the best way to optimize so that expensive work isn't being done every time my widget gets initialized?

what are your thoughts?

**Comment by brianegan** [comment]
Hi Dustin,

I might not have the full context, but it sounds like your Data layer might be the right place to handle this. For example, if your Epic calls an API to fetch data, you could create a class that wraps your API and caches fetched results in memory. Then, when you request the same resource from the API, the data layer could decide if it should return the cached version, or if a certain amount of time has passed, to flush the cached version and fetch from the network again.

Does that work for your scenario?

**Comment by brianegan** [comment]
Hey Dustin, did this answer help or need more guidance? Happy to help further if need be, or close the issue if you think it's resolved.

**Comment by dustin-graham** [comment]
@brianegan that's very helpful. I'm going to keep that logic in the data layer, as you said. Thanks for the help.
