### ISSUE TITLE
Open different sample apps separately

### ISSUE THREAD

**Issue by eddywm** [brianegan/flutter_architecture_samples#46]
How do you get to open each different sample application separately in an IDE, apparently they are tightly coupled and it's almost impossible for me to open each sample separately so that I can focus on learning source code of one sample at a time.

One project importing packages from an outside different project, that coupling makes it very hard to study the different architectures proposed here.

**Comment by brianegan** [comment]
Heya Eddy,

The code for each sample lives in a different directory under the examples folder. You can open each app found in the example ddirectory in it's own editor window if that helps, or open the whole project so you can hop between examples quickly.

Most of the samples also depend on 3 common libraries: a Core lib that defines things such as colors, the Todos Repository for loading / persisting data, and the integration test suite. I split these out so they could be shared across all apps and so I could document the patterns being used. 

 
Hope that helps, let me know if I can help any further.

**Comment by eddywm** [comment]
Oh thanks for the kindness and the fast reply.

The problem I was facing when trying to open each app separately in Intellij, was the red underlining due to referencing paths out of the currently opened project.
It was distracting for me.

**Comment by brianegan** [comment]
Sure thing, glad I could help! 

I don't think there should be a problem opening the projects separately, but I've definitely seen IntelliJ showing red lines underneath classes and functions that I definitely exist. When this happens, I tend to open up the `pubspec.yaml`, run "Get Dependencies," and run the "Restart Dart Analysis Server" action after it finishes fetching the dependencies. This generally fixes the problem. 

Kind of a cave-man approach to solving the issue, haha, but works for me :) Might be worth giving it a shot and seeing if it helps out on your side!
