### ISSUE TITLE
Redux example: filter button invisible, but still enabled

### ISSUE THREAD

**Issue by Tyrn** [brianegan/flutter_architecture_samples#55]
Appbar filter button on `Stats` page is invisible by design, yet still responsive.

`filter_button.dart` (a possible remedy):
```
    return IgnorePointer(
      ignoring: !visible,
      child: AnimatedOpacity(
        opacity: visible ? 1.0 : 0.0,
...
      ),
    );
```
I am not sure this is the best solution, but it works.

**Comment by brianegan** [comment]
Oh, good call, thanks for letting me know :) I bet this affects most of the samples. I'll play around with some options, but this one doesn't look too bad!
