### ISSUE TITLE
built_redux some tests failing

### ISSUE THREAD

**Issue by mmcc007** [brianegan/flutter_architecture_samples#57]
FYI: 3 out of 19 tests in built_redux are currently failing. 

BTW: I can do a pull request for CI test and code coverage report if interested from [this](https://github.com/mmcc007/flutter_architecture_samples) fork.

**Comment by brianegan** [comment]
Thanks for the heads up! Yep, those changes look great. I've been meaning to do that for ages... Please submit a PR :)

In the meantime, I'll fix up those broken tests!

**Comment by brianegan** [comment]
All right, pushed up a fix for the tests. Please feel free to submit a PR whenever you have time :) I
