### ISSUE TITLE
How to run app

### ISSUE THREAD

**Issue by Chozzle** [brianegan/flutter_architecture_samples#59]
Hi Brian. I'm pretty new to Flutter and I think this repo is a great source. However I can't get it to compile and run on an emulator. Could you provide guidance on how to do that? I'm using android studio and ```flutter packages get``` crashes on the top level flutter_architecture_samples folder. Inner folders can compile but fail at runtime.

**Comment by Chozzle** [comment]
I figured it out. I needed to run ```flutter packages get``` on the depending packages, then run with ```flutter run --target=lib/main_local_storage.dart```. I might put a PR up for this

**Comment by sgon00** [comment]
Hi, even if the app is not runnable now, I think this issue should not be closed. Can you please open it? The readme still does not mention this at all.
