### ISSUE TITLE
[Redux] Can't get dropdown to work properly on Statelesswidget 

### ISSUE THREAD

**Issue by ekevjn** [brianegan/flutter_architecture_samples#60]
I using redux for flutter so every presentation is stateless but i can't get dropdown menu to work property since i can't change it's state to trigger flutter to rebuild the dropdown part when choose value from dropdown. 

I trying to implement dropdown menu for [this](https://github.com/brianegan/flutter_architecture_samples/blob/master/example/redux/lib/presentation/add_edit_screen.dart) screen.

My code look something like this:
```
List<String> _suppliers = <String>['Apple', 'Google'];
  String _supplier = 'Apple';

DropdownButton(
                  key: _supplierKey,
                  value: _supplier,
                  items: _suppliers.map((String value) {
                    return new DropdownMenuItem<String>(
                      value: value,
                      child: new Text(value),
                    );
                  }).toList(),
                  onChanged: (String newValue) {
                    _supplier = newValue;
                  }),
```

I don't know if i implemented it right or anyway to workaround? Any help would be appreciate. Thanks you.

**Comment by brianegan** [comment]
Key @ekevjn, did this help out? If so, I'll close this out. If not, happy to keep it open and help a bit more.
