### ISSUE TITLE
Scoped model: is it bad to call Model.notifyListeners "unnecessarily"?

### ISSUE THREAD

**Issue by kinex** [brianegan/flutter_architecture_samples#64]
Assume I have a `Model` class with 10 properties each calling `notifyListeners` in their setter method.  `Model` class has also an `Update` method which updates all those properties triggering 10 subsequent `notifyListeners` calls. 

Then I use the `Model` class in a Widget tree which references only one of the `Model` properties. Therefore calling `Update` method causes 9 unnecessary updates to the Widget tree.

Is this a real issue I should pay attention to or can I ignore this due to e.g. some Flutter optimization?

**Comment by brianegan** [comment]
Hey there! Overall, Flutter is fast, but calling `notifyListeners()` could cause performance issues if a lot of Widgets are listening to the `Model`, especially on slower devices. Why? That would require all Widgets that are connected to the `Model` via a `ScopedModelDescendant`. That said, as with all performance questions, I'd definitely measure first and see if it's a problem, then perform an optimization.

If you find that ya need to optimize, you could definitely change the update function to set all of private values, then calls `notifyListeners()` at the end.

**Comment by kinex** [comment]
Ok. Thank you for providing these architecture samples, really useful for a new Flutter developer. My current plan is to use Redux/Firebase in my first Flutter app.
