### ISSUE TITLE
Can I add a ReduRx example?

### ISSUE THREAD

**Issue by leocavalcante** [brianegan/flutter_architecture_samples#66]
Before I start coding, I'd like to make sure that a PR with a [ReduRx](https://github.com/leocavalcante/ReduRx) sample has some chance to get listed.
[Here is some resource on the lib in Flutter](https://medium.com/@leocavalcante/tutorial-handling-state-in-flutter-with-redurx-b4d50c647e4a).

**Comment by brianegan** [comment]
Hey there -- sure thing! This repo is meant as a way to provide different implementations so we can compare and contrast them as a community using an "Apples to Apples" comparison as much as possible.

Please do your best to ensure your app follows the spec, and submit a PR when you're ready for feedback :)

https://github.com/brianegan/flutter_architecture_samples/blob/master/app_spec.md

**Comment by leocavalcante** [comment]
Awesome, thank you. I'll make sure that specs are properly implemented.
