### ISSUE TITLE
Flutter driver integration test does not test data input

### ISSUE THREAD

**Issue by mmcc007** [brianegan/flutter_architecture_samples#74]
Inputting a new task is not implemented in the current integration test. 

FYI: It appears to be possible now. The fix for me was to convert to a stateful widget and use only one global key for the form instead of additional global keys for the individual fields. I was able to get it working in the redux project. The added integration test passes. 

Happy to try to fix it in the other projects and submit a PR at some point if this sounds useful (might need some pointers for other projects). Please let me know 👍

**Comment by brianegan** [comment]
Oh, that'd be great! Glad to hear it's possible now :)

**Comment by mmcc007** [comment]
Fixed with #75
