### ISSUE TITLE
An MVC Contribution                                                                                

### ISSUE THREAD

**Issue by Andrious** [brianegan/flutter_architecture_samples#77]
Good Evening, Brian

I was hoping to make a further contribution to this wonderful project. Recently built a plugin, [mvc_pattern](https://pub.dartlang.org/packages/mvc_pattern), as a offering to our fledgling Flutter community. It provides a framework using the MVC design pattern.
 
I have cloned [Flutter Arichitecture Samples](https://github.com/brianegan/flutter_architecture_samples) and included a new example under a branch called mvc_sample. 

Currently, I have my contribution in a 'copy' on my own account: [Flutter Arichitecture Samples.](https://github.com/Andrious/flutter_architecture_samples)

Please, I offer this for your consideration.

Best Regards,

Greg Perry

**Comment by brianegan** [comment]
Hey Perry! My apologies on the delay -- busy work / travel times these past two weeks.

I'd be more than happy to see an MVC contribution :) 

This repo is meant as a way to provide different implementations so we can compare and contrast them as a community using an "Apples to Apples" comparison as much as possible. Therefore, pPlease do your best to ensure your app follows the spec, and submit a PR when you're ready for feedback :)

https://github.com/brianegan/flutter_architecture_samples/blob/master/app_spec.md

**Comment by Andrious** [comment]
@Brain,

Thank-you for taking in my contribution, Brian.
Providing these different architectural concepts is a great endeavor.

As instructed, I did supply my name and such to the [Readme](https://github.com/brianegan/flutter_architecture_samples) file, but, didn't have access to the Flutter Architecture Samples [webpage](http://fluttersamples.com/) itself to add the links there.

**Comment by brianegan** [comment]
Hey hey -- thanks again for the reminder, my bad.

https://github.com/brianegan/flutter_architecture_samples/commit/80a93b726634fab2d6f7e3b6261143a137d64a05
