### ISSUE TITLE
Flutter Redux Navigator returns null

### ISSUE THREAD

**Issue by sudipdas1** [brianegan/flutter_architecture_samples#80]
Hi,
I am new to flutter and redux and I am getting the below error when trying to navigate from middleware. Please help.

I/flutter ( 4808): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 4808): The following NoSuchMethodError was thrown attaching to the render tree:
I/flutter ( 4808): The method 'pushNamed' was called on null.
I/flutter ( 4808): Receiver: null
I/flutter ( 4808): Tried calling: pushNamed("/login")
I/flutter ( 4808):
I/flutter ( 4808): When the exception was thrown, this was the stack:
I/flutter ( 4808): #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
I/flutter ( 4808): #1      createUserLogin.<anonymous closure> (package:built_redux_sample/middleware/middleware.dart:92:31)
I/flutter ( 4808): #2      MiddlewareBuilder.add.<anonymous closure> (package:built_redux/src/middleware.dart:42:14)
I/flutter ( 4808): #3      MiddlewareBuilder.build.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:built_redux/src/middleware.dart:68:26)
I/flutter ( 4808): #4      ActionDispatcher.call (package:built_redux/src/action.dart:32:29)
I/flutter ( 4808): #5      checkFile.<anonymous closure> (package:built_redux_sample/middleware/middleware.dart:78:22)
I/flutter ( 4808): #6      MiddlewareBuilder.add.<anonymous closure> (package:built_redux/src/middleware.dart:42:14)
I/flutter ( 4808): #7      MiddlewareBuilder.build.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:built_redux/src/middleware.dart:68:26)
I/flutter ( 4808): #8      ActionDispatcher.call (package:built_redux/src/action.dart:32:29)
I/flutter ( 4808): #9      BuiltReduxAppState.initState (package:built_redux_sample/main.dart:68:19)
I/flutter ( 4808): #10     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3787:58)
I/flutter ( 4808): #11     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3653:5)
I/flutter ( 4808): #12     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2937:14)
I/flutter ( 4808): #13     Element.updateChild (package:flutter/src/widgets/framework.dart:2740:12)
I/flutter ( 4808): #14     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:901:16)
I/flutter ( 4808): #15     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:872:5)
I/flutter ( 4808): #16     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:818:17)
I/flutter ( 4808): #17     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2253:19)
I/flutter ( 4808): #18     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:817:13)
I/flutter ( 4808): #19     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:709:7)
I/flutter ( 4808): #20     runApp (package:flutter/src/widgets/binding.dart:748:7)
I/flutter ( 4808): #21     main (package:built_redux_sample/main.dart:40:3)
I/flutter ( 4808): #22     main (file:///Users/sudip/development/projects/flutter/test-flutter/lib/main.dart:5:3)
I/flutter ( 4808): #23     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:289:19)
I/flutter ( 4808): #24     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
I/flutter ( 4808): ════════════════════════════════════════════════════════════════════════════════════════════════════

**main.dart**
library built_redux_sample;

import 'package:built_redux/built_redux.dart';
import 'package:built_redux_sample/actions/actions.dart';
import 'package:built_redux_sample/containers/add_node.dart';
import 'package:built_redux_sample/localization.dart';
import 'package:built_redux_sample/middleware/middleware.dart';
import 'package:built_redux_sample/models/models.dart';
import 'package:built_redux_sample/presentation/home_screen.dart';
import 'package:built_redux_sample/presentation/login_screen.dart';
import 'package:built_redux_sample/presentation/login.dart';
import 'package:built_redux_sample/reducers/reducers.dart';
import 'package:flutter/material.dart';
import 'package:test/test.dart';
import 'package:flutter_built_redux/flutter_built_redux.dart';
import 'package:test/src/keys.dart';

void main() {
  runApp(BuiltReduxApp());
}

class BuiltReduxApp extends StatefulWidget {

  final store = Store<AppState, AppStateBuilder, AppActions>(
    reducerBuilder.build(),
    AppState.loading(),
    AppActions(),
    middleware: [
      createStoreMiddleware(),
    ],
  );

  @override
  State<StatefulWidget> createState() {
    return BuiltReduxAppState();
  }
}

class BuiltReduxAppState extends State<BuiltReduxApp> {
  Store<AppState, AppStateBuilder, AppActions> store;

  BuiltReduxApp() {}

  @override
  void initState() {
    store = widget.store;
    store.actions.checkFileExists();
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return ReduxProvider(
      store: store,
      child: MaterialApp(
        title: BuiltReduxLocalizations().appTitle,
        theme: ArchSampleTheme.theme,
        navigatorKey: ArchSampleKeys.navKey,
        localizationsDelegates: [
          ArchSampleLocalizationsDelegate(),
          BuiltReduxLocalizationsDelegate(),
        ],
        routes: {
          ArchSampleRoutes.login: (context) {
            return LoginScreen(key: ArchSampleKeys.loginScreen,onSubmitLogin: store.actions.loginRequestAction,);
          },
          ArchSampleRoutes.home: (context) {
            return HomeScreen(key: ArchSampleKeys.homeScreen);
          },
          ArchSampleRoutes.addNode: (context) {
            return AddNode();
          },
        },
      ),
    );
  }
}

**middleware.dart**(not the full code)

import 'package:built_redux/built_redux.dart';
import 'package:built_redux_sample/actions/actions.dart';
import 'package:built_redux_sample/data/repository.dart';
import 'package:built_redux_sample/models/models.dart';
import 'package:built_redux_sample/data/user_storage.dart';
import 'package:path_provider/path_provider.dart';
import 'package:test/src/keys.dart';
import 'package:test/src/routes.dart';

Middleware<AppState, AppStateBuilder, AppActions> createStoreMiddleware([
  Repository repository = const Repository(),
  UserStorage userStorage = const UserStorage('__built_redux_user_app__',
      getApplicationDocumentsDirectory),

]) {
  final navigatorKey = ArchSampleKeys.navKey;

  return (MiddlewareBuilder<AppState, AppStateBuilder, AppActions>()
        ..add(AppActionsNames.checkFileExists, 
            checkFile<bool>(userStorage))
        ..add(AppActionsNames.loginAction,
            createUserLogin<Null>(navigatorKey)))
      .build();
}

MiddlewareHandler<AppState, AppStateBuilder, AppActions, bool> checkFile<bool>(
    UserStorage userStorage) {
  return (MiddlewareApi<AppState, AppStateBuilder, AppActions> api,
      ActionHandler next, Action<bool> action) {

    if (api.state.isLoading) {
      if(userStorage.checkEmpty() != null){
         api.actions.loginAction();
      }
    }

    next(action);
  };
}

MiddlewareHandler<AppState, AppStateBuilder, AppActions, T> createUserLogin<T>(
    navigatorKey) {
  return (MiddlewareApi<AppState, AppStateBuilder, AppActions> api,
      ActionHandler next, Action<T> action) {
        print('going..');
    next(action);
    navigatorKey.currentState.pushNamed(ArchSampleRoutes.login);  //error in this line while executing
  };
}

**Comment by brianegan** [comment]
Hey there, sorry I missed this! Hrm, it's a bit tough to say what the issue is in this case. Just to make sure: Is the `navigatorKey` attached to the `MaterialApp` before the Middelware attempts to navigate?

E.g. are you firing a navigation action before the Widget tree has been constructed? That's the only thing I could see in your code that might be the problem, since the rest looks Ok to me reading the code as best I can.
