### ISSUE TITLE
Using RefreshIndicator with built_redux

### ISSUE THREAD

**Issue by jkyon** [brianegan/flutter_architecture_samples#84]
Hi
First of all, thank you all for this library, it is just amazing. I´ve enjoyed learning this architecture and implementing it on a project in the company where a I´m working now. 

I'm really new to Flutter and Dart, so I have a question. I want to use a pull to refresh which sends an action and retrieves a new set of items from the rest api via the middleware. I need to use RefreshIndicator, but the indicator needs a Future passed to it (onRefresh) that resolves when the action has finished. Is there any way that I can use the existing stock widget to start and stop based on actions?

Thank you in advance!

**Comment by zerox1212** [comment]
Something like the refresh indicator used here? https://github.com/gildaswise/flutter_phone_auth

**Comment by brianegan** [comment]
Hey there -- I generally follow this type of Pattern: https://github.com/brianegan/flutter_redux/issues/6

This is for the Redux package, but the principles for built_redux would be the same. Hope that helps!
