### ISSUE TITLE
Explanation of Entities

### ISSUE THREAD

**Issue by zerox1212** [brianegan/flutter_architecture_samples#86]
I'm trying hard to learn Flutter and dart. These examples are great. However one question I have is about the purpose of the "entity" pattern that is used.

Why do you have a `TodoEntity` and then a model for `Todo`? It seems like it would be much more straight forward to remove the entity and just work with model. Can't you add another constructor that takes in json or something and parse it there directly?

**Comment by brianegan** [comment]
Hey there -- the reason I have a separate "TodoEntity" for the Data Layer is to ensure each app can implement the `Todo` class in any way they see fit. In some examples, Todo is Mutable. In other cases, it's immutable. In some cases, it's created with `built_value`, other times it's not. 

Therefore, the TodoEntity is used to map from a "Todo" (or whatever Model each app wants to use) to a TodoEntity that the Data layer knows how to store / load from persistence.

If you have a different requirement and you know that the Model / Entity will be the same in each layer (Widget, Domain, and Data layer), you can forego creating a separate class. In fact, I'd recommend just using a single "Todo" model to follow the DRY principle! I just needed that extra abstraction in this case.
