### ISSUE TITLE
Vanilla + Firestore Help

### ISSUE THREAD

**Issue by zerox1212** [brianegan/flutter_architecture_samples#88]
I'm trying to take the Vanilla example and implement getting the todos via Firestore. I'm using the redux_firestore example for help. I have most of it refactored but I'm not sure how to handle the lack of `loadTodos()` method since the reactive design doesn't load like that. Redux is quite different so I'm having trouble identifying how to adapt the code.

``` dart
class VanillaApp extends StatefulWidget {
  final ReactiveTodosRepository repository; /// <use reactive repository

  VanillaApp({@required this.repository});

  @override
  State<StatefulWidget> createState() {
    return VanillaAppState();
  }
}

class VanillaAppState extends State<VanillaApp> {
  AppState appState = AppState.loading();

  @override
  void initState() {
    super.initState();

    widget.repository.loadTodos().then((loadedTodos) { /// < how to handle this with reactive design?
      setState(() {
        appState = AppState(
          todos: loadedTodos.map(Todo.fromEntity).toList(),
        );
      });
    }).catchError((err) {
      setState(() {
        appState.isLoading = false;
      });
    });
  }
```
Thanks

**Comment by brianegan** [comment]
Hey hey -- in that case, you can treat the "Init" call like an action! So in this case, something like an "InitApp" action. You can then intercept that action in a Middleware and make the appropriate call to the backend to load the data.

This article describes the general process: https://github.com/johnpryan/redux.dart/blob/master/doc/async.md

In your case, it would look something like this:

```dart
class LoadTodos {}

class LoadTodosSuccess {
  final List<Todo> todos;

  LoadTodosSuccess(this.todos);
}

class LoadTodosFailed {}

store.dispatch(InitAppAction());

// In a middleware function... 
void fetchTodosMiddleware(Store<AppState> store, action, NextDispatcher next) {
  // If our Middleware encounters a `FetchTodoAction`
  if (action is InitAppAction) {    
    // Use the api to fetch the todos
    repository.loadTodos().then((List<Todo> todos) {
      store.dispatch(new LoadTodosSuccess(todos));
    }).catchError((Exception error) {
      store.dispatch(new LoadTodosFailed(error));
    });  
  }
  
  // Make sure our actions continue on to the reducer.
  next(action);
}
```

Hope this helps!

**Comment by zerox1212** [comment]
Thanks for the info. This info seems more for use with redux, which I'm not using. Are you saying I need to create a similar Middleware class that calls `setState()` when it returns? I'm still having a hard time understanding how to link the Firebase realtime DB `Stream` to updating the UI.

Also when using Firebase realtime DB the persistence (even when offline) is handled automatically, so I feel like I should be able to simplify the examples where we don't need our own repository class. Firebase library is the repository. I think I just need some helper functions to query the data I need?

**Comment by zerox1212** [comment]
Upon further reading it looks like it should be possible to use a `StreamBuilder` widget instead of explicitly calling a load method. I'll give both a try.
