### ISSUE TITLE
Use of InitBloc function rather than a Bloc Provider

### ISSUE THREAD

**Issue by S1r-Lanzelot** [brianegan/flutter_architecture_samples#93]
In the following line:
https://github.com/brianegan/flutter_architecture_samples/blob/c3b66660faadfa848a1f7447221854fcd65bc2c3/example/bloc_flutter/lib/widgets/todo_list.dart#L46

the bloc is instantiated via a function that is passed to the stateful todo `DetailScreen`. This works fine however I am wonder why was a `TodoBlocProvider` class within `DetailScreen` was not used instead? We could get the dependencies through the Injector class the same way... but instead would have a nice provider that we could call from nested widgets off of the detail screen, correct?

This part confused me so I am wondering if there is any benefit in this method vs using a "nested" provider. Is this method of bloc instantiation preferred when no child widgets will require the bloc?

Furthermore, it appears that these Blocs are created per "screen", is that the typical approach?

Thanks for the library/help.

**Comment by S1r-Lanzelot** [comment]
This article helped answer my questions for future people who come across this issue: https://www.didierboelens.com/2018/12/reactive-programming---streams---bloc---practical-use-cases/

**Comment by brianegan** [comment]
> Is this method of bloc instantiation preferred when no child widgets will require the bloc?

That's just how I do it. If you find providers work well, or want to always use a Generic provider (like the one discussed in that article), no problemo!

  > Furthermore, it appears that these Blocs are created per "screen", is that the typical approach?

The original advice from the BLoC inventor is to create a BLoC for each "Complex enough" component. So, it's a judgement call on what that means. I do think it makes more sense to split blocs apart than to have too many "God BLoCs" that have too many responsibilities, but how and where you break BLoCs apart is always going to require a bit of thought.
