### ISSUE TITLE
Unable to run firestore_redux with firebase_rtdb_flutter_repository

### ISSUE THREAD

**Issue by kinggolf** [brianegan/flutter_architecture_samples#97]
Hi @brianegan - it's been too long. Happy New Year! 

I think what @mmcc007 has done with firebase_rtdb_flutter_repository working with firestore_redux is very cool, but unfortunately I am unable to get it to work.

I've forked and cloned the latest flutter_architecture_samples repo and am able to successfully run firestore_redux based on firebase_flutter_repository, however, when I switch to firebase_rtdb_flutter_repository I get both an IDE error, FirebaseDatabase undefined on FirebaseReactiveTodosRepository, and a compile time error when I run the app.

I have followed the clear directions in the firebase_rtdb_flutter_repository [README](https://github.com/kinggolf/flutter_architecture_samples/blob/master/example/firebase_rtdb_flutter_repository/README.md), changing pubspec.yaml in firestore_redux:
```
firebase_flutter_repository:
    path: ../firebase_rtdb_flutter_repository
```
and changing main.dart in firestore_redux:
```
todosRepository ??
                FirebaseReactiveTodosRepository(FirebaseDatabase.instance),
```

I have tried upgrading to latest firebase_database version in firebase_rtdb_flutter_repository.

I know I'm pointing main.dart to the firebase_rtdb_flutter_repository because I can rename both FirebaseReactiveTodosRepository and FirebaseUserRepository in this repo and my IDE requires the same change in main.dart.

I've tried all kinds of other crazy things, but I'm simply stumped. Appreciate any assistance on this.

Thanks all.

**Comment by mmcc007** [comment]
Sorry u ran into this.

I gave it a shot on android with the current repo and it still seems to work fine (round-trip from RTDB and back). 

Other than what is in README, and the standard set-up for firebase (google-services.json and change the application_id in app/build.gradle), I had to switch the cloud_firestore package to firebase_database package in lib/main.dart. `flutter analyze` reported no problems.

If not resolved, send ur `flutter doctor -v` and compiler error.

Thnx

**Comment by kinggolf** [comment]
Simple enough - all working with `firebase_database` import in `main.dart`. Thank you.

Like I said previously, very nice example of code reuse and could actually be a practical solution for someone converting from RTDB to Firestore or in reverse.

Cheers!
