### ISSUE TITLE
Bloc example BlocProvider

### ISSUE THREAD

**Issue by cgomezmendez** [brianegan/flutter_architecture_samples#98]
Given that this tries to convey the best practices, is there any reason why the bloc provider it's class specific instead of a generic one? like one in this article? https://www.didierboelens.com/2018/12/reactive-programming---streams---bloc---practical-use-cases/#1-bloc-provider-and-inheritedwidget

```
Type _typeOf<T>() => T;

abstract class BlocBase {
  void dispose();
}

class BlocProvider<T extends BlocBase> extends StatefulWidget {
  BlocProvider({
    Key key,
    @required this.child,
    @required this.bloc,
  }): super(key: key);

  final Widget child;
  final T bloc;

  @override
  _BlocProviderState<T> createState() => _BlocProviderState<T>();

  static T of<T extends BlocBase>(BuildContext context){
    final type = _typeOf<_BlocProviderInherited<T>>();
    _BlocProviderInherited<T> provider = 
            context.ancestorInheritedElementForWidgetOfExactType(type)?.widget;
    return provider?.bloc;
  }
}

class _BlocProviderState<T extends BlocBase> extends State<BlocProvider<T>>{
  @override
  void dispose(){
    widget.bloc?.dispose();
    super.dispose();
  }
  
  @override
  Widget build(BuildContext context){
    return new _BlocProviderInherited<T>(
      bloc: widget.bloc,
      child: widget.child,
    );
  }
}

class _BlocProviderInherited<T> extends InheritedWidget {
  _BlocProviderInherited({
    Key key,
    @required Widget child,
    @required this.bloc,
  }) : super(key: key, child: child);

  final T bloc;

  @override
  bool updateShouldNotify(_BlocProviderInherited oldWidget) => false;
}
```

**Comment by brianegan** [comment]
Thanks for writing in :) 

Tis a fair point -- since I've only got one BLoC to pass down in this manner, a generic solution seemed like overkill. 

Overall, it's a great article, so perhaps I'll keep it as-is for now (I think it might be simpler for newcomers?) but link to that article for the more generic solution. What are your thoughts on that?

**Comment by cgomezmendez** [comment]
Ah ok, I understand. Seems good to me, I asked because I'm new to bloc arch and I'm using the sample here kind of like my guide. Thanks for answering. pointing out to a more generic solution while still maintaining the simpler version to newcomers seems like a good solution.

**Comment by mmcc007** [comment]
@cgomezmendez If this issue is resolved, please close.
